### ISSUE TITLE
Cannot import RESTClient

### ISSUE THREAD

**Issue by Hackmodford** [snowskeleton/ynam#23]
I'm trying to get this to run on macOS since, I assume, I am unable to run the docker image until I have populated the various config files.

After installing pyenv in order to install ynam via `pip install ynam` I get this error when trying to run `ynam --quickstart`

For Docker, have you considered passing in the required values via environment variables? Or provide documentation on how to manually populate the yaml files?

```
❯ ynam --quickstart
Traceback (most recent call last):
  File "/Users/hackmodford/.pyenv/versions/3.10.4/bin/ynam", line 5, in <module>
    from ynam.main import main
  File "/Users/hackmodford/.pyenv/versions/3.10.4/lib/python3.10/site-packages/ynam/main.py", line 5, in <module>
    from .mint_api import MintAPI
  File "/Users/hackmodford/.pyenv/versions/3.10.4/lib/python3.10/site-packages/ynam/mint_api.py", line 5, in <module>
    from mintapi import RESTClient, SeleniumBrowser
ImportError: cannot import name 'RESTClient' from 'mintapi' (/Users/hackmodford/.pyenv/versions/3.10.4/lib/python3.10/site-packages/mintapi/__init__.py)
```

**Comment by Hackmodford** [comment]
Issue also happened when following instructions in a python docker container, so it's not related to macOS

**Comment by snowskeleton** [comment]
Happy New Year!

> After installing pyenv in order to install ynam via pip install ynam I get this error when trying to run ynam --quickstart
...
ImportError: cannot import name 'RESTClient' from 'mintapi' (/Users/hackmodford/.pyenv/versions/3.10.4/lib/python3.10/site-packages/mintapi/__init__.py)


Did you install [my fork](https://github.com/snowskeleton/mintapi/) of the mintapi package? The import error you're getting is usually because pypi tries to be helpful and install the canonical version from [mintapi/mintapi](https://github.com/mintapi/mintapi/), which doesn't yet have my changes. (PR pending)

> For Docker, have you considered passing in the required values via environment variables? …

I hadn't, actually, mostly because I've never used that aspect of Docker.
I'd welcome a PR, if you have time to devote to that.

>  … Or provide documentation on how to manually populate the yaml files?

(assuming you mean the json-formated `~/.ynamrc`, as this project doesn't use yaml)
Can you elaborate a bit on why this would be needed?

**Comment by bayonhealth** [comment]
> Happy New Year!
> 
> > After installing pyenv in order to install ynam via pip install ynam I get this error when trying to run ynam --quickstart
> > ...
> > ImportError: cannot import name 'RESTClient' from 'mintapi' (/Users/hackmodford/.pyenv/versions/3.10.4/lib/python3.10/site-packages/mintapi/**init**.py)
> 
> Did you install [my fork](https://github.com/snowskeleton/mintapi/) of the mintapi package? The import error you're getting is usually because pypi tries to be helpful and install the canonical version from [mintapi/mintapi](https://github.com/mintapi/mintapi/), which doesn't yet have my changes. (PR pending)
> 
> > For Docker, have you considered passing in the required values via environment variables? …
> 
> I hadn't, actually, mostly because I've never used that aspect of Docker. I'd welcome a PR, if you have time to devote to that.
> 
> > … Or provide documentation on how to manually populate the yaml files?
> 
> (assuming you mean the json-formated `~/.ynamrc`, as this project doesn't use yaml) Can you elaborate a bit on why this would be needed?

Thank you, that fixed my problem with the REST error, but now I'm running into a new problem. After punching in my YNAB API key and choosing my budget, I get the following error messages:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/ynam/ynab_api.py", line 653, in _decode
    return answer['data']
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/ynam", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/ynam/main.py", line 20, in main
    handleArgs()
  File "/opt/homebrew/lib/python3.9/site-packages/ynam/main.py", line 48, in handleArgs
    sys.exit(run())
  File "/opt/homebrew/lib/python3.9/site-packages/ynam/quickstart.py", line 44, in run
    updateStash('ynab_account_id', usersChoice(ynapi.get_accounts())['id'])
  File "/opt/homebrew/lib/python3.9/site-packages/ynam/ynab_api.py", line 127, in get_accounts
    return _decode(self._get(url))['accounts']
  File "/opt/homebrew/lib/python3.9/site-packages/ynam/ynab_api.py", line 655, in _decode
    raise Exception(answer['error'])
Exception: {'id': '404.2', 'name': 'resource_not_found', 'detail': 'Resource not found'}

**Comment by snowskeleton** [comment]
I'm guessing that's the same error as #22 , which got fixed just the other day. `pip install -U ynam` an drerun

**Comment by bayonhealth** [comment]
> I'm guessing that's the same error as #22 , which got fixed just the other day. `pip install -U ynam` and rerun

Yep, that fixed my issue, but still running into other issues when running the ynam command. Will go back through the instructions and see what may be going on.

**Comment by snowskeleton** [comment]
I'm closing this issue as resolved. Feel free to open up another issue with any further problems
