### ISSUE TITLE
Exits on run in docker

### ISSUE THREAD

**Issue by BCtopics** [snowskeleton/ynam#33]
I'm having this error, and nothing is importing to YNAB. The first run didn't give any errors, however did not import either.

`2023-02-17 13:34:17 INFO:mintapi:The Multifactor Method soft-token supplied is not available.
2023-02-17 13:34:37 INFO:mintapi:Not on Account Selection Screen
2023-02-17 13:34:38 INFO:mintapi:Not on Secondary MFA Password Screen
2023-02-17 13:35:04 ERROR:mintapi:Message: 
2023-02-17 13:35:04 Stacktrace:
2023-02-17 13:35:04 #0 0x55c7ae713d93 <unknown>
2023-02-17 13:35:04 #1 0x55c7ae4e22d7 <unknown>
2023-02-17 13:35:04 #2 0x55c7ae51ecaa <unknown>
2023-02-17 13:35:04 #3 0x55c7ae51edb1 <unknown>
2023-02-17 13:35:04 #4 0x55c7ae55c8f4 <unknown>
2023-02-17 13:35:04 #5 0x55c7ae54261d <unknown>
2023-02-17 13:35:04 #6 0x55c7ae55a619 <unknown>
2023-02-17 13:35:04 #7 0x55c7ae542353 <unknown>
2023-02-17 13:35:04 #8 0x55c7ae511e40 <unknown>
2023-02-17 13:35:04 #9 0x55c7ae513038 <unknown>
2023-02-17 13:35:04 #10 0x55c7ae7678be <unknown>
2023-02-17 13:35:04 #11 0x55c7ae76b8f0 <unknown>
2023-02-17 13:35:04 #12 0x55c7ae74bf90 <unknown>
2023-02-17 13:35:04 #13 0x55c7ae76cb7d <unknown>
2023-02-17 13:35:04 #14 0x55c7ae73d578 <unknown>
2023-02-17 13:35:04 #15 0x55c7ae791348 <unknown>
2023-02-17 13:35:04 #16 0x55c7ae7914d6 <unknown>
2023-02-17 13:35:04 #17 0x55c7ae7ab341 <unknown>
2023-02-17 13:35:04 #18 0x7f370d126609 start_thread
2023-02-17 13:35:04 Traceback (most recent call last):
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/ynam/main.py", line 24, in main
2023-02-17 13:35:04     mint_transactions = mint_api.get_transactions(start_date=arg('days'))
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/ynam/mint_api.py", line 48, in get_transactions
2023-02-17 13:35:04     client.authorize(self.cookies(), self.key())
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/ynam/mint_api.py", line 58, in cookies
2023-02-17 13:35:04     return ast.literal_eval(file.read())
2023-02-17 13:35:04   File "/usr/lib/python3.8/ast.py", line 59, in literal_eval
2023-02-17 13:35:04     node_or_string = parse(node_or_string, mode='eval')
2023-02-17 13:35:04   File "/usr/lib/python3.8/ast.py", line 47, in parse
2023-02-17 13:35:04     return compile(source, filename, mode, flags,
2023-02-17 13:35:04   File "<unknown>", line 0
2023-02-17 13:35:04     
2023-02-17 13:35:04     ^
2023-02-17 13:35:04 SyntaxError: unexpected EOF while parsing
2023-02-17 13:35:04 
2023-02-17 13:35:04 During handling of the above exception, another exception occurred:
2023-02-17 13:35:04 
2023-02-17 13:35:04 Traceback (most recent call last):
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/mintapi/signIn.py", line 368, in sign_in
2023-02-17 13:35:04     handle_same_page_username_password(driver, email, password)
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/mintapi/signIn.py", line 457, in handle_same_page_username_password
2023-02-17 13:35:04     email_input = driver.find_element(By.ID, "ius-userid")
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 830, in find_element
2023-02-17 13:35:04     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
2023-02-17 13:35:04     self.error_handler.check_response(response)
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
2023-02-17 13:35:04     raise exception_class(message, screen, stacktrace)
2023-02-17 13:35:04 selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ius-userid"]"}
2023-02-17 13:35:04   (Session info: headless chrome=110.0.5481.77)
2023-02-17 13:35:04 Stacktrace:
2023-02-17 13:35:04 #0 0x55c7ae713d93 <unknown>
2023-02-17 13:35:04 #1 0x55c7ae4e22d7 <unknown>
2023-02-17 13:35:04 #2 0x55c7ae51ecaa <unknown>
2023-02-17 13:35:04 #3 0x55c7ae51edb1 <unknown>
2023-02-17 13:35:04 #4 0x55c7ae55c8f4 <unknown>
2023-02-17 13:35:04 #5 0x55c7ae54261d <unknown>
2023-02-17 13:35:04 #6 0x55c7ae55a619 <unknown>
2023-02-17 13:35:04 #7 0x55c7ae542353 <unknown>
2023-02-17 13:35:04 #8 0x55c7ae511e40 <unknown>
2023-02-17 13:35:04 #9 0x55c7ae513038 <unknown>
2023-02-17 13:35:04 #10 0x55c7ae7678be <unknown>
2023-02-17 13:35:04 #11 0x55c7ae76b8f0 <unknown>
2023-02-17 13:35:04 #12 0x55c7ae74bf90 <unknown>
2023-02-17 13:35:04 #13 0x55c7ae76cb7d <unknown>
2023-02-17 13:35:04 #14 0x55c7ae73d578 <unknown>
2023-02-17 13:35:04 #15 0x55c7ae791348 <unknown>
2023-02-17 13:35:04 #16 0x55c7ae7914d6 <unknown>
2023-02-17 13:35:04 #17 0x55c7ae7ab341 <unknown>
2023-02-17 13:35:04 #18 0x7f370d126609 start_thread
2023-02-17 13:35:04 
2023-02-17 13:35:04 
2023-02-17 13:35:04 During handling of the above exception, another exception occurred:
2023-02-17 13:35:04 
2023-02-17 13:35:04 Traceback (most recent call last):
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/mintapi/browser.py", line 115, in login_and_get_token
2023-02-17 13:35:04     self.status_message = sign_in(
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/mintapi/signIn.py", line 375, in sign_in
2023-02-17 13:35:04     handle_different_page_username_password(driver, email)
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/mintapi/signIn.py", line 471, in handle_different_page_username_password
2023-02-17 13:35:04     email_input = WebDriverWait(driver, 20).until(
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/support/wait.py", line 95, in until
2023-02-17 13:35:04     raise TimeoutException(message, screen, stacktrace)
2023-02-17 13:35:04 selenium.common.exceptions.TimeoutException: Message: 
2023-02-17 13:35:04 Stacktrace:
2023-02-17 13:35:04 #0 0x55c7ae713d93 <unknown>
2023-02-17 13:35:04 #1 0x55c7ae4e22d7 <unknown>
2023-02-17 13:35:04 #2 0x55c7ae51ecaa <unknown>
2023-02-17 13:35:04 #3 0x55c7ae51edb1 <unknown>
2023-02-17 13:35:04 #4 0x55c7ae55c8f4 <unknown>
2023-02-17 13:35:04 #5 0x55c7ae54261d <unknown>
2023-02-17 13:35:04 #6 0x55c7ae55a619 <unknown>
2023-02-17 13:35:04 #7 0x55c7ae542353 <unknown>
2023-02-17 13:35:04 #8 0x55c7ae511e40 <unknown>
2023-02-17 13:35:04 #9 0x55c7ae513038 <unknown>
2023-02-17 13:35:04 #10 0x55c7ae7678be <unknown>
2023-02-17 13:35:04 #11 0x55c7ae76b8f0 <unknown>
2023-02-17 13:35:04 #12 0x55c7ae74bf90 <unknown>
2023-02-17 13:35:04 #13 0x55c7ae76cb7d <unknown>
2023-02-17 13:35:04 #14 0x55c7ae73d578 <unknown>
2023-02-17 13:35:04 #15 0x55c7ae791348 <unknown>
2023-02-17 13:35:04 #16 0x55c7ae7914d6 <unknown>
2023-02-17 13:35:04 #17 0x55c7ae7ab341 <unknown>
2023-02-17 13:35:04 #18 0x7f370d126609 start_thread
2023-02-17 13:35:04 
2023-02-17 13:35:04 Traceback (most recent call last):
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/ynam/main.py", line 24, in main
2023-02-17 13:35:04     mint_transactions = mint_api.get_transactions(start_date=arg('days'))
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/ynam/mint_api.py", line 48, in get_transactions
2023-02-17 13:35:04     client.authorize(self.cookies(), self.key())
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/ynam/mint_api.py", line 58, in cookies
2023-02-17 13:35:04     return ast.literal_eval(file.read())
2023-02-17 13:35:04   File "/usr/lib/python3.8/ast.py", line 59, in literal_eval
2023-02-17 13:35:04     node_or_string = parse(node_or_string, mode='eval')
2023-02-17 13:35:04   File "/usr/lib/python3.8/ast.py", line 47, in parse
2023-02-17 13:35:04     return compile(source, filename, mode, flags,
2023-02-17 13:35:04   File "<unknown>", line 0
2023-02-17 13:35:04     
2023-02-17 13:35:04     ^
2023-02-17 13:35:04 SyntaxError: unexpected EOF while parsing
2023-02-17 13:35:04 
2023-02-17 13:35:04 During handling of the above exception, another exception occurred:
2023-02-17 13:35:04 
2023-02-17 13:35:04 Traceback (most recent call last):
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/mintapi/signIn.py", line 368, in sign_in
2023-02-17 13:35:04     handle_same_page_username_password(driver, email, password)
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/mintapi/signIn.py", line 457, in handle_same_page_username_password
2023-02-17 13:35:04     email_input = driver.find_element(By.ID, "ius-userid")
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 830, in find_element
2023-02-17 13:35:04     return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
2023-02-17 13:35:04     self.error_handler.check_response(response)
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
2023-02-17 13:35:04     raise exception_class(message, screen, stacktrace)
2023-02-17 13:35:04 selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="ius-userid"]"}
2023-02-17 13:35:04   (Session info: headless chrome=110.0.5481.77)
2023-02-17 13:35:04 Stacktrace:
2023-02-17 13:35:04 #0 0x55c7ae713d93 <unknown>
2023-02-17 13:35:04 #1 0x55c7ae4e22d7 <unknown>
2023-02-17 13:35:04 #2 0x55c7ae51ecaa <unknown>
2023-02-17 13:35:04 #3 0x55c7ae51edb1 <unknown>
2023-02-17 13:35:04 #4 0x55c7ae55c8f4 <unknown>
2023-02-17 13:35:04 #5 0x55c7ae54261d <unknown>
2023-02-17 13:35:04 #6 0x55c7ae55a619 <unknown>
2023-02-17 13:35:04 #7 0x55c7ae542353 <unknown>
2023-02-17 13:35:04 #8 0x55c7ae511e40 <unknown>
2023-02-17 13:35:04 #9 0x55c7ae513038 <unknown>
2023-02-17 13:35:04 #10 0x55c7ae7678be <unknown>
2023-02-17 13:35:04 #11 0x55c7ae76b8f0 <unknown>
2023-02-17 13:35:04 #12 0x55c7ae74bf90 <unknown>
2023-02-17 13:35:04 #13 0x55c7ae76cb7d <unknown>
2023-02-17 13:35:04 #14 0x55c7ae73d578 <unknown>
2023-02-17 13:35:04 #15 0x55c7ae791348 <unknown>
2023-02-17 13:35:04 #16 0x55c7ae7914d6 <unknown>
2023-02-17 13:35:04 #17 0x55c7ae7ab341 <unknown>
2023-02-17 13:35:04 #18 0x7f370d126609 start_thread
2023-02-17 13:35:04 
2023-02-17 13:35:04 
2023-02-17 13:35:04 During handling of the above exception, another exception occurred:
2023-02-17 13:35:04 
2023-02-17 13:35:04 Traceback (most recent call last):
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/mintapi/browser.py", line 115, in login_and_get_token
2023-02-17 13:35:04     self.status_message = sign_in(
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/mintapi/signIn.py", line 375, in sign_in
2023-02-17 13:35:04     handle_different_page_username_password(driver, email)
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/mintapi/signIn.py", line 471, in handle_different_page_username_password
2023-02-17 13:35:04     email_input = WebDriverWait(driver, 20).until(
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/support/wait.py", line 95, in until
2023-02-17 13:35:04     raise TimeoutException(message, screen, stacktrace)
2023-02-17 13:35:04 selenium.common.exceptions.TimeoutException: Message: 
2023-02-17 13:35:04 Stacktrace:
2023-02-17 13:35:04 #0 0x55c7ae713d93 <unknown>
2023-02-17 13:35:04 #1 0x55c7ae4e22d7 <unknown>
2023-02-17 13:35:04 #2 0x55c7ae51ecaa <unknown>
2023-02-17 13:35:04 #3 0x55c7ae51edb1 <unknown>
2023-02-17 13:35:04 #4 0x55c7ae55c8f4 <unknown>
2023-02-17 13:35:04 #5 0x55c7ae54261d <unknown>
2023-02-17 13:35:04 #6 0x55c7ae55a619 <unknown>
2023-02-17 13:35:04 #7 0x55c7ae542353 <unknown>
2023-02-17 13:35:04 #8 0x55c7ae511e40 <unknown>
2023-02-17 13:35:04 #9 0x55c7ae513038 <unknown>
2023-02-17 13:35:04 #10 0x55c7ae7678be <unknown>
2023-02-17 13:35:04 #11 0x55c7ae76b8f0 <unknown>
2023-02-17 13:35:04 #12 0x55c7ae74bf90 <unknown>
2023-02-17 13:35:04 #13 0x55c7ae76cb7d <unknown>
2023-02-17 13:35:04 #14 0x55c7ae73d578 <unknown>
2023-02-17 13:35:04 #15 0x55c7ae791348 <unknown>
2023-02-17 13:35:04 #16 0x55c7ae7914d6 <unknown>
2023-02-17 13:35:04 #17 0x55c7ae7ab341 <unknown>
2023-02-17 13:35:04 #18 0x7f370d126609 start_thread
2023-02-17 13:35:04 
2023-02-17 13:35:04 
2023-02-17 13:35:04 The above exception was the direct cause of the following exception:
2023-02-17 13:35:04 
2023-02-17 13:35:04 Traceback (most recent call last):
2023-02-17 13:35:04   File "/usr/local/bin/ynam", line 8, in <module>
2023-02-17 13:35:04     sys.exit(main())
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/ynam/main.py", line 26, in main
2023-02-17 13:35:04     mint_api.updateAuth()
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/ynam/mint_api.py", line 66, in updateAuth
2023-02-17 13:35:04     browser = self.browser(
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/mintapi/browser.py", line 55, in __init__
2023-02-17 13:35:04     self.login_and_get_token(
2023-02-17 13:35:04   File "/usr/local/lib/python3.8/dist-packages/mintapi/browser.py", line 136, in login_and_get_token
2023-02-17 13:35:04     raise Exception(msg) from e
2023-02-17 13:35:04 Exception: Could not sign in to Mint. Current page: https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3Da80ba49f-9b8d-4183-ab60-b3b1b86aa723
`

Thanks!

**Comment by BCtopics** [comment]
This was fixed by adding two factor auth to my account. Perhaps using it without that is broken?

**Comment by CraigDevJohnson** [comment]
I'm getting the same error. "2023-02-23 15:27:33 INFO:mintapi:The Multifactor Method soft-token supplied is not available."

I tried with and without MFA and I get it every time I try to run in Docker. Not sure why it isn't working without MFA, but I must be entering the mfa seed wrong during the quickstart?

I get to the QR code and key. I copy the keys which is 8 sets of 4 characters and paste that notepad to remove any linebreaks or spaces and then copy/paste that into the quickstart prompt.

**Comment by snowskeleton** [comment]
Running without MFA is not officially supported. I haven't actively taken steps to prevent it, but with my own setup, not having MFA caused innumerable issues. I should perhaps update the readme to more clearly make that point.

> I get to the QR code and key. I copy the keys which is 8 sets of 4 characters and paste that notepad to remove any linebreaks or spaces and then copy/paste that into the quickstart prompt.
Just to make sure, you're completing the MFA setup with Mint, correct? The exact wording you gave indicates you may have simply copied the code and backed out of the setup, which  would cause failure. 

Assuming you completed the MFA setup correctly with Authy or some other app, the other most common failure point is entering different codes into Authy vs ynam. For example, if you use the QR code to enter into Authy and then copy/paste into ynam, you may be getting different seeds for each. To ensure this is not the case, manually copy/paste the code into Authy rather than using the QR code feature. You were right to remove spaces/linebreakes, though.

**Comment by CraigDevJohnson** [comment]
Hmmm. So I used 1Password and I did scan the QR code instead of entering the code (1Password doesn't allow you to enter it manually from what I can tell). But I checked it and I can see the MFA seed code in 1Password and I entered that into Authy as a test and its generating the same 6 digit TOTP. I tried deleting the secrets.json and deleted any existing containers/images and started fresh. Entered my login and the verified MFA seed with --quickstart but I'm still getting the "INFO:mintapi:The Multifactor Method soft-token supplied is not available." error. 

Though I think the issue now is my Intuit account (and probably has been for a bit tbh). It took me a bit to figure out exactly what was needed and I tried quite a few times via the Python script and Docker with and without MFA so I've probably flagged my account. If I log in with my cached browser, it lets me in. But if I open an incognito browser and try to log in, I get a "Too many invalid attempts, account is locked out for 1145 minutes." message so that is probably the issue, right? I guess I was way too aggressive with my troubleshooting... I'll let it sit for a few days and try again. Appreciate the information.

**Comment by snowskeleton** [comment]
Any resolution after letting it sit for the timeout period?

**Comment by CraigDevJohnson** [comment]
Not yet. After waiting a few days I ran it and got Incorrect Password a few times. Which doesn't make sense because I can copy paste the password from the secrets.json and it works fine in my regular browser. But after trying a few times, I'm getting the account locked again. Though that might be a cookie issue? Cause I can open an incognito window and log in just fine. Are the selenium_cookes/session and chromedirver the only files that I would need to delete in order to 'clear' the cache/cookies? I tried deleting them and still run into it saying I'm locked.

**Comment by snowskeleton** [comment]
It's strange you would get an "incorrect password" error when, like you said, copy/paste shows it to be correct. You may be on the right track with a cookie issue. Theoretically, all you need to delete are the `session`,`chromedriver`, `cookies` files. However, I had some strange authentication issues on my mac that persisted until I rebuilt my python virtual environment, so you might try that too. (Alternatively, if you're not already using a virtual environment, consider using one.)

**Comment by CraigDevJohnson** [comment]
Huh, I had never heard of a virtual python enviornment. I'll have to look into converting to doing that. 

I am having the weirdest error. So I managed to get past the password issue. After the page loading and it got to the prompt for my password, I clicked log in a different way and had it send me a code to my email to log in. Got that done and then it showed "It looks like you use a different User ID for Mint. Try <parts of my email>" and stops there. However, if I click right below it to use my same email, it prompts for password and auth code and I'm in. Its like it is trying to log into a mint version only of my account instead of my intuit account or something? Specifically the error:
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\craig\AppData\Local\Programs\Python\Python310\Scripts\ynam-script.py", line 33, in <module>
    sys.exit(load_entry_point('ynam==0.4.0.post0', 'console_scripts', 'ynam')())
  File "C:\Users\craig\AppData\Local\Programs\Python\Python310\lib\site-packages\ynam\main.py", line 26, in main
    mint_api.updateAuth()
  File "C:\Users\craig\AppData\Local\Programs\Python\Python310\lib\site-packages\ynam\mint_api.py", line 66, in updateAuth
    browser = self.browser(
  File "C:\Users\craig\AppData\Local\Programs\Python\Python310\lib\site-packages\mintapi\browser.py", line 55, in __init__
    self.login_and_get_token(
  File "C:\Users\craig\AppData\Local\Programs\Python\Python310\lib\site-packages\mintapi\browser.py", line 136, in login_and_get_token
    raise Exception(msg) from e
Exception: Could not sign in to Mint. Current page: https://accounts.intuit.com/index.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3D51f5ab46-81df-4e98-9f5e-177e58ab8d78%3Futm_medium%3Ddirect%26cta%3Dnav_login_dropdown%26ivid%3D51f5ab46-81df-4e98-9f5e-177e58ab8d78&appfabric=true&iux_initial_error=MINT_WRONG_ACCOUNT&iux_initial_error_content=cr***********on%40g****.**m


I think I just need to spend some time to convert to a virtual environment and try again.

**Comment by CraigDevJohnson** [comment]
Oh, I didn't realize it was best to use a Mint only account. I've been trying with the Intuit one, which did end up creating a Mint account with the same email. I did as you suggested, and it worked! Thank you!
