### ISSUE TITLE
ynam all of a sudden now working

### ISSUE THREAD

**Issue by bayonhealth** [snowskeleton/ynam#37]
I've had ynam working percetly for many months now and all of a sudden it seems broken. Nothing has changed with my workflow and everything looks good over at Mint.com. Any suggestions?

Traceback (most recent call last):
  File "/opt/homebrew/bin/ynam", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/ynam/main.py", line 32, in main
    ynab_transactions = ynab_api.get_account_transactions(
  File "/opt/homebrew/lib/python3.9/site-packages/ynam/ynab_api.py", line 498, in get_account_transactions
    return [
  File "/opt/homebrew/lib/python3.9/site-packages/ynam/ynab_api.py", line 499, in <listcomp>
    YNABTransaction.from_dict(xt)
  File "/opt/homebrew/lib/python3.9/site-packages/ynam/ynab_api.py", line 42, in from_dict
    return cls(**{
  File "<string>", line 15, in __init__
  File "/opt/homebrew/lib/python3.9/site-packages/ynam/ynab_api.py", line 31, in __post_init__
    if len(self.payee_name) >= 100:
TypeError: object of type 'NoneType' has no len()

**Comment by bayonhealth** [comment]
I ran "pip install git+https://github.com/mintapi/mintapi" and it upgrade from 2.11>2.14, but still same error. I ran the ynam quickstart again and no issues there, but same errors when running it now.

**Comment by snowskeleton** [comment]
Running through `quickstart` doesn't exercise the Mint login flow. You can use `ynam --update-mint-auth` instead.

The way you updated looks valid, assuming you're not using a virtual environment or container of some sort.

Also your Apple Card may have become unlinked, which happens every 90 days or so and can have various consequences. It shows up if you try to interact with the account in the Mint web UI.
