### ISSUE TITLE
KeyError: 'fiData'

### ISSUE THREAD

**Issue by tonyvarin** [snowskeleton/ynam#42]
Trying this out for the first time. I will be setting up in Docker, but currently just testing with yam -x. I have MFA seed setup and API key of course.

Output:

```
[tonyvarin@rhel9 ~]$ ynam -x
INFO:mintapi:Not on Account Selection Screen
INFO:mintapi:Not on Secondary MFA Password Screen
Traceback (most recent call last):
  File "/home/tonyvarin/.local/lib/python3.9/site-packages/ynam/main.py", line 24, in main
    mint_transactions = mint_api.get_transactions(start_date=arg('days'))
  File "/home/tonyvarin/.local/lib/python3.9/site-packages/ynam/mint_api.py", line 53, in get_transactions
    [logger.debug(item['fiData']) for item in items]
  File "/home/tonyvarin/.local/lib/python3.9/site-packages/ynam/mint_api.py", line 53, in <listcomp>
    [logger.debug(item['fiData']) for item in items]
KeyError: 'fiData'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tonyvarin/.local/bin/ynam", line 8, in <module>
    sys.exit(main())
  File "/home/tonyvarin/.local/lib/python3.9/site-packages/ynam/main.py", line 27, in main
    mint_transactions = mint_api.get_transactions(start_date=arg('days'))
  File "/home/tonyvarin/.local/lib/python3.9/site-packages/ynam/mint_api.py", line 53, in get_transactions
    [logger.debug(item['fiData']) for item in items]
  File "/home/tonyvarin/.local/lib/python3.9/site-packages/ynam/mint_api.py", line 53, in <listcomp>
    [logger.debug(item['fiData']) for item in items]
KeyError: 'fiData'
```

**Comment by snowskeleton** [comment]
are you running this in a graphical environment? If not, using `-x` (for graphics) doesn't do anything. If yes, what's happening in the browser during this failure?

**Comment by tonyvarin** [comment]
Hi! Thank you for such a quick response. I'm running in a graphical environment (Remote Desktop into RHEL 9 to be specific). Chrome opens up, has a few banners about warning about using this version and that it's being controlled by automated test software. It opens Mint, logs in with MFA (neat to watch), gets to my account Overview page, sits there for about 10 seconds, and quits out.

And... just tested it to give you this info. No errors, just worked this time. Sorry for the false alarm.
