### ISSUE TITLE
easyconfig that is installed doesn't seem to be the correct one?

### ISSUE THREAD

**Issue by hrpomrx** [snowskeleton/ynam#9]
``` 
ynam --quickstart
Traceback (most recent call last):
  File "/home/pi/ynam/bin/ynam", line 5, in <module>
    from ynam.main import main
  File "/home/pi/ynam/lib/python3.9/site-packages/ynam/main.py", line 5, in <module>
    from .mint_api import dispenseMints
  File "/home/pi/ynam/lib/python3.9/site-packages/ynam/mint_api.py", line 2, in <module>
    from .utils import recent
  File "/home/pi/ynam/lib/python3.9/site-packages/ynam/utils.py", line 2, in <module>
    from easyConfig.main import Configer
ModuleNotFoundError: No module named 'easyConfig'
```

**Comment by snowskeleton** [comment]
Pull again from pypi and give it a try.

**Comment by snowskeleton** [comment]
Hmm. I'll take another look at this.

**Comment by hrpomrx** [comment]
Awesome! Seems the arg flow in main is maybe not picking up the quickstart logic.

**Comment by snowskeleton** [comment]
Everything seems to be working now. I tested it with and without the files in place, and both were able to log in and import transactions.
There's also an update to snowskeleton/mintapi that you'll need to pick up.

**Comment by hrpomrx** [comment]
Thanks for looking into this….I updated and re-ran. Entered mint username, mint password, skipped mfa, then entered ynab api key, and get this:

```
Default to only option
Traceback (most recent call last):
  File "/home/pi/.local/bin/ynam", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.9/site-packages/ynam/main.py", line 18, in main
    handleArgs()
  File "/home/pi/.local/lib/python3.9/site-packages/ynam/main.py", line 37, in handleArgs
    run()
  File "/home/pi/.local/lib/python3.9/site-packages/ynam/quickstart.py", line 49, in run
    stash.update('budget_id', usersChoice(ynapi.getBudgets())['id'])
TypeError: 'NoneType' object is not subscriptable
pi@raspberrypi:~ $ 
```

**Comment by hrpomrx** [comment]
I should add, there wasn’t a prompt for Budget Id.

**Comment by snowskeleton** [comment]
The way it chooses a budget ID is by querying YNAB for what budgets you have available. Do you have any budgets set up in YNAB yet? If you don't have any, it might have returned 0 and I was expecting more than 0.

**Comment by hrpomrx** [comment]
I do actually - have one named “My Budget”. I tried renaming it to just one word, no spaces, but same error.

**Comment by snowskeleton** [comment]
I would double check your API key then (it's stored in `~/.ynamrc`), and maybe generate a new one to see if that works.

**Comment by hrpomrx** [comment]
So, I created a new one and the error goes away and it shows me a choice of 2 budgets  now. It doesn’t seem to like you just having the 1 default budget? Anyhow it seems to be working now I think. Thanks for your help and for creating this! I’m sure it’ll be a big time-saver until Apple/Goldman do something useful about it.

**Comment by hrpomrx** [comment]
Still having more issues when running ynam to get txns, I’ll post error below when at laptop.

**Comment by hrpomrx** [comment]
Here goes…fwiw, I’m running the pi in headless mode;  not using MFA with Mint.

```
Enter 0–7: 7                                                                                                                       
selected: Apple Card                                                                                                               
pi@raspberrypi:~ $ ynam --days 1                                                                                                   
Traceback (most recent call last):                                                                                                 
  File "/home/pi/.local/lib/python3.9/site-packages/ynam/mint_api.py", line 41, in key                                             
    with open(self.keypath, 'r') as file:                                                                                          
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.mintapi/api_key'                                                
                                                                                                                                   
During handling of the above exception, another exception occurred:                                                                
                                                                                                                                   
Traceback (most recent call last):                                                                                                 
  File "/home/pi/.local/bin/ynam", line 8, in <module>                                                                             
    sys.exit(main())                                                                                                               
  File "/home/pi/.local/lib/python3.9/site-packages/ynam/main.py", line 23, in main                                                
    mints = mapi.dispenseMints()                                                                                                   
  File "/home/pi/.local/lib/python3.9/site-packages/ynam/mint_api.py", line 17, in dispenseMints                                   
    key = self.key()                                                                                                               
  File "/home/pi/.local/lib/python3.9/site-packages/ynam/mint_api.py", line 44, in key                                             
    self.updateAuth()                                                                                                              
  File "/home/pi/.local/lib/python3.9/site-packages/ynam/mint_api.py", line 49, in updateAuth                                      
    bowser = self.browser(                                                                                                         
  File "/home/pi/.local/lib/python3.9/site-packages/mintapi/browser.py", line 55, in __init__                                      
    self.login_and_get_token(                                                                                                      
  File "/home/pi/.local/lib/python3.9/site-packages/mintapi/browser.py", line 110, in login_and_get_token                          
    self.driver = driver or _create_web_driver_at_mint_com(                                                                        
  File "/home/pi/.local/lib/python3.9/site-packages/mintapi/signIn.py", line 313, in _create_web_driver_at_mint_com                
    driver = Chrome(                                                                                                               
  File "/usr/local/lib/python3.9/dist-packages/seleniumrequests/request.py", line 144, in __init__                                 
    super(RequestsSessionMixin, self).__init__(*args, **kwargs)     
File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__                       
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,           
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__ 
    self._execute_child(args, executable, preexec_fn, close_fds, 
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename) 
OSError: [Errno 8] Exec format error: '/home/pi/chromedriver'    
pi@raspberrypi:~ $ 
```

**Comment by snowskeleton** [comment]
The last line `OSError: [Errno 8] Exec format error: '/home/pi/chromedriver'` seems to indicate there's a problem with your chromium installation. Do you have the most recent version of chrome with `apt install chromium-browser chromium-chromedriver`, or whatever the pi equivalent is?

**Comment by hrpomrx** [comment]
Figures. I assumed that was for —graphics only, obviously assumed wrong. Will check.

**Comment by snowskeleton** [comment]
I can see how you'd make that assumption.

For future reference, Selenium is used for the first login every hour or so. If we've logged in recently with Selenium and saved the cookies and api_key, then we can send REST calls without using Selenium.

As ynam is currently configured, it will always try the REST call first. If that fails (such as with `FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.mintapi/api_key'`, because you haven't logged in yet), then ynam tries to take the browser through the login process to get new cookies and api_key.

**Comment by hrpomrx** [comment]
Got it. Thanks for the explanation and your efforts to build this!

**Comment by snowskeleton** [comment]
I'm glad it's working! I'll go ahead and close this issue now, but feel free to open if you find anything else.

**Comment by hrpomrx** [comment]
So I do actually have the chromium packages installed, but running ynam seems to install a rogue chromedriver in the home dir not for this arch, hence the exec format error.  Opened as a separate issue, so no need to reopen this.
